# Generated by Django 3.2.4 on 2021-08-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.CharField(max_length=200)),
                ('YourEmail', models.EmailField(max_length=100)),
                ('YourSubject', models.CharField(max_length=200)),
                ('YourMessage', models.TextField()),
            ],
        ),
    ]
